#version: 2.1
## aws-s3 orb
#commands:
  #sync:
    #description: "A simple encapsulation of doing an s3 sync"
    #parameters:
      #from:
        #type: string
      #to:
        #type: string
      #overwrite:
        #default: false
        #type: boolean
    #steps:
      #- run:
          #name: Deploy to S3
          #command: aws s3 sync << parameters.from >> << parameters.to >><<# parameters.overwrite >> --delete<</ parameters.overwrite >>
#workflows:
    #version: 2
    #workflow:
      #jobs:
        #- commands
        #- sync

version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.0 #imports the s3 orb in the circleci namespace
workflows:
  build-test-deploy:
    jobs:
      - deploy2s3:
        steps:
          - aws-s3/sync: #invokes the sync command declared in the s3 orb
              from: 
             to: "s3://mybucket_uri"
              overwrite: true
