version: 2.1

jobs:
  hello-build:
    docker:
      - image: circleci/buildpack-deps:curl-browsers
    steps:
      - run:
          command: echo "Hello, build!"
workflows:
  hello-workflow:
    jobs:
      - hello-build
      #- hello/hello-build
  #version: 2
  
